image: gitpod/workspace-gecko

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

tasks:
  - init: ./mach build && ./mach build-backend -b CompileDB
    command: ./mach run

vscode:
  extensions:
    - webfreak.debug@0.25.0:1RYXlY/ZLAfnftc0HaYsDQ==
